#!/bin/bash
#
# Copyright (c) 2017, 2021 by Matthew Jacob
# All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of The version 2 GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#
# Matthew Jacob
# Feral Software
# 253 Lowell Street
# Redwood City, CA 94062
# USA
#
# gpl at feralsw com
#
function doexit
{
 echo $*
 exit 1
}

BASE=$(pwd)/usr/src/kernels
set -o errexit
set -o pipefail
[[ -z $1 ]] || bsys=$1
[[ -n $1 ]] || bsys=$(uname -r|sed 's/-.*//')
cat md5sum.versions | while read b md5s; do
 rel=$(echo $b | sed 's/linux-//')
 xsys=$(echo $rel | sed 's/-.*$//')
 [[ $bsys = $xsys ]] || continue
 url=$(grep $rel kernel_rpms.txt)
 nurl=$(echo $url | wc -l)
 [[ $nurl -eq 1 ]] || doexit too many urls: $nurl
 rm -rf ${BASE}/$rel
 curl -s $url | rpm2cpio | cpio -idmu --quiet
 [[ -d ${BASE}/$rel ]] || doexit cannot find ${BASE}/$rel
 cp versions/nbd.c.${md5s} nbd.c
 if [[ -f patches/linux-${rel}.patch ]]; then
  patch -p1 < patches/linux-${rel}.patch
 fi
 make KMOD=${BASE}/$rel KVERS=$rel pkg
 rm -rf ${BASE}/$rel
done
git diff nbd.c |patch -s -p1 -R
